name: Node.js CI

on: [push, pull_request]

env: DATABASE_URL: 'https://fake.com'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        registry-url: 'https://registry.npmjs.org/'
        scope: '@yourscope'
        always-auth: true
    - name: Install Dependencies
      run: yarn
    - name: Type Checking
      run: yarn run tsc --noEmit
    - name: Lint
      run: yarn run lint
