name: Node.js CI

on: [push, pull_request]

env: DATABASE_URL: 'https://fake.com'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: yarn
    - name: Type Checking
      run: yarn run tsc --noEmit
    - name: Lint
      run: yarn run lint
    - name: Print Environment Variable
      run: echo $MY_ENV_VAR